<?php

namespace TheLoneBlackSheep\Component\TeamA\Administrator\View\News;

\defined('_JEXEC') or die;

use Joomla\CMS\Helper\ContentHelper;
use Joomla\CMS\Toolbar\Toolbar;
use Joomla\CMS\Toolbar\ToolbarHelper;
use Joomla\CMS\Language\Text;

class HtmlView
	extends \Joomla\CMS\MVC\View\HtmlView
{
  protected $pagination;

  protected $teamaNews;

	public function display( $tpl = null ) {

    $this->teamaNews = $this->get('Items');
    $this->pagination = $this->get('Pagination');

    if(!count($this->teamaNews) && $this->get('IsEmptyState')) {
      $this->setLayout('emptystate');
    }

    $this->addToolbar();

		parent::display( $tpl ); // TODO: Change the autogenerated stub
	}

	protected function addToolbar(){
	  $toolbar = Toolbar::getInstance();
	  ToolbarHelper::title(Text::_('COM_TEAMA_MANAGER_NEWS'), 'manage teama');
    $globalCanDo = ContentHelper::getActions('com_teama');
	  $newsCanDo = ContentHelper::getActions('com_teama','news');

    if($globalCanDo->get('news.create') ||
       $newsCanDo->get('news.create')
    )
      $toolbar->addNew('onenews.add');
  }
}