<?php

namespace TheLoneBlackSheep\Component\TeamA\Administrator\View\News;

\defined('_JEXEC') or die;

class HtmlView
	extends \Joomla\CMS\MVC\View\HtmlView
{
	public function display( $tpl = null ) {
		parent::display( $tpl ); // TODO: Change the autogenerated stub
	}
}