<?php

namespace TheLoneBlackSheep\Component\TeamA\Site\View\News;

\defined('_JEXEC') or die;

use Joomla\CMS\MVC\View\HtmlView as BaseHtmlView;

class HtmlView
	extends BaseHtmlView{

	function display( $tpl = null ) {
		parent::display( $tpl ); // TODO: Change the autogenerated stub
	}

}