# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
# this is a group variables to manage versioning number for all pipelines in the same repo
  - group: version_variables
  - name: semanticVersion
    value: $[counter(variables['semverPrefix'], 0)]

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: PowerShell@2
  displayName: Set Build Number
  inputs:
    targetType: inline
    script: |
      echo 'Starting Setting build Number'
      Write-host " - Current Build Number : $($env:BUILD_BUILDNUMBER)"
      Write-host " - Semantic Build Number : $($env:SEMVERPREFIX).$($env:SEMANTICVERSION).0"
      Write-host "##vso[build.updatebuildnumber]$($env:SEMVERPREFIX).$($env:SEMANTICVERSION).0"

- task: NodeTool@0
  displayName: Installing nodejs latest version
  inputs:
   versionSpec: '>=10.x'
   checkLatest: true

- task: Npm@1
  displayName: Install lerna globally
  inputs: 
    command: custom
    customCommand: install lerna -g

- task: Npm@1
  displayName: Install all Root dependencies
  inputs:
   command: install
- task: Npm@1
  displayName: Install all other dependencies
  inputs:
   command: custom
   customCommand: install packages/*
      
- task: Npm@1
  displayName: Bootstrap project
  inputs:
    command: custom
    customCommand: run bootstrap

- task: Npm@1
  displayName: Launch build
  inputs:
    command: custom
    customCommand: run build