<?php

namespace TheLoneBlackSheep\Component\TeamA\Administrator\View\Departments;

use Joomla\CMS\Factory;
use Joomla\CMS\Toolbar\Toolbar;
use Joomla\CMS\Toolbar\ToolbarHelper;

class HtmlView
	extends \Joomla\CMS\MVC\View\HtmlView {

	protected $pagination;

	protected $items;

	private $filterForm;

	public function display( $tpl = null ) {
		$this->pagination = $this->get('Pagination');
		$this->filterForm = $this->get('FilterForm');
		$this->items = $this->get('Items');

		if( !count($this->items) &&
		    $this->get('IsEmptyState')) {
			$this->setLayout('emptystate');
		}

		$this->addToolbar();

		parent::display( $tpl ); // TODO: Change the autogenerated stub
	}

	protected function addToolbar(){
		$toolbar = Toolbar::getInstance();
		$app = Factory::getApplication();
		$user = $app->getIdentity();

		ToolbarHelper::title(Text::_('COM_TEAMA_DEPARTMENTS_NEWS'), 'manage teama');

		if($user->authorise('departments.create',
			'com_teama'))
			$toolbar->addNew('departments.add');

		if($user->authorise('departments.delete',
			'com_teama'))
			$toolbar->delete('departments.delete');
	}
}