<?php

namespace TheLoneBlackSheep\Component\TeamA\Administrator\Controller;

\defined('_JEXEC') or die;

use Joomla\CMS\MVC\Controller\FormController;

class DepartmentController
extends FormController {
	protected $view_list="departments";

	public function display( $cachable = false, $urlparams = array() ) {
		return parent::display( $cachable, $urlparams ); // TODO: Change the autogenerated stub
	}
}