<?php

namespace TheLoneBlackSheep\Component\TeamA\Administrator\Controller;

use Joomla\CMS\MVC\Controller\BaseController;

class NewsController
	extends BaseController
{
	protected $default_view = 'News';

	public function display( $cachable = false, $urlparams = array() ) {
		return parent::display( $cachable, $urlparams ); // TODO: Change the autogenerated stub
	}
}