<?php

use Joomla\CMS\Factory;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Toolbar\Toolbar;
use Joomla\CMS\Toolbar\ToolbarHelper;

class HtmlView
	extends \Joomla\CMS\MVC\View\HtmlView
{
	protected $form;

	protected $item;

	public function display($tpl = NULL) {
		$this->form = $this->get('Form');
		$this->item = $this->get('Item');

		$this->addToolBar();

		parent::display($tpl); // TODO: Change the autogenerated stub
	}

	public function addToolBar(){
		Factory::getApplication()->input->set('hidemainmenu',
			false);
		$isNew = ($this->item->id == 0);
		ToolbarHelper::title($isNew ?
			Text::_('COM_TEAMA_MANAGER_DEPARTMENT_NEW'):
			Text::_('COM_TEAMA_MANAGER_DEPARTMENT_EDIT'),
			'manage departments');

		ToolbarHelper::apply('department.apply');
		ToolbarHelper::cancel('department.cancel',
			'JTOOLBAR_CLOSE');
	}

}