<?php

namespace TheLoneBlackSheep\Component\TeamA\Administrator\Dispatcher;

use Joomla\CMS\Dispatcher\ComponentDispatcher;

class Dispatcher
	extends ComponentDispatcher
{

	public function dispatch() {
		parent::dispatch(); // TODO: Change the autogenerated stub
	}
}