<?php

namespace TheLoneBlackSheep\Component\TeamA\Site\View\Onenews;

\defined('_JEXEC') or die('Restricted Access');

use Joomla\CMS\MVC\View\HtmlView as BaseHtmlView;

class HtmlView extends BaseHtmlView
{
  protected $item;

  public function display($tpl = NULL) {
    $this->item = $this->get('Item');
    parent::display($tpl); // TODO: Change the autogenerated stub
  }

}