<?php

use Joomla\CMS\Factory;

/**
 * @package     ${NAMESPACE}
 * @subpackage
 *
 * @copyright   A copyright
 * @license     A "Slug" license name e.g. GPL2
 */
class JFormFieldBSHelpRequestObjectives extends JFormField
{
	public function __construct($form = null)
	{
		parent::__construct($form);
		$this->layout = 'default';
	}

	function getInput()
	{
		return parent::getInput(); // TODO: Change the autogenerated stub
	}

	protected function getLayoutPaths()
	{
		$app = Factory::getApplication();
		$paths = parent::getLayoutPaths(); // TODO: Change the autogenerated stub
		if(!is_array($paths)){
			$paths = [];
		}

		$componentFieldLayoutPath = $app->isClient('site') ?
			JPATH_SITE . '/components/com_teama/layouts/fields/BSHelpRequestObjectives/':
			JPATH_ADMINISTRATOR . '/components/com_teama/layouts/fields/BSHelpRequestObjectives';
		$paths[] = $componentFieldLayoutPath;
		return $paths;
	}

	function getRenderer($layoutId = 'default')
	{
		return parent::getRenderer($layoutId); // TODO: Change the autogenerated stub
	}

	function render($layoutId, $data = array())
	{
		return parent::render($layoutId, $data); // TODO: Change the autogenerated stub
	}
}