<?php

namespace TheLoneBlackSheep\Component\TeamA\Administrator\Model;

use Joomla\CMS\Factory;
use Joomla\CMS\MVC\Model\AdminModel;

class DepartmentModel
	extends AdminModel {

	public $typeAlias = 'com_teama.department';

	public function getForm( $data = array(), $loadData = true ) {
		$app = Factory::getApplication();
		$form = $this->loadForm(
			$this->typeAlias,
			'department',
			[ 'control' => 'jform', 'load_data' => $loadData ]);
		if(empty($form)){
			return false;
		}
	}

	protected function loadFormData() {
		$app = Factory::getApplication();
		$data = $this->getItem();
		$this->preprocessData($this->typeAlias, $data);
		return $data;
	}

	public function validate( $form, $data, $group = null ) {
		return parent::validate( $form, $data, $group ); // TODO: Change the autogenerated stub
	}

	protected function canDelete( $record ) {
		return parent::canDelete( $record ); // TODO: Change the autogenerated stub
	}

}