<?php

namespace TheLoneBlackSheep\Component\TeamA\Administrator\Model;

\defined('_JEXEC') or die;

use Joomla\CMS\MVC\Factory\MVCFactoryInterface;

class DepartmentsModel
	extends TeamAListModel
{
	public function __construct($config = [], MVCFactoryInterface $factory = NULL) {
		if(empty($config['filter_fields'])){
			$config['filter_fields'] = [
				'name','a.name'
			];
		}
		$this->paginationLimit = 20;
		parent::__construct($config, $factory);
	}

	protected $filterFormName = 'filter_departments';

	protected function getListQuery() {
		return parent::getListQuery(); // TODO: Change the autogenerated stub
	}

	protected function getEmptyStateQuery() {
		return parent::getEmptyStateQuery(); // TODO: Change the autogenerated stub
	}

	public function delete($pks = []){
		if(is_array($pks) && count($pks) > 0){
			$db = $this->getDbo();
			$query = "DELETE #__teama_departments FROM #__teama_departments 
				WHERE id IN (" . implode(',', $pks) . ")";
			$db->setQuery($query);
			$db->execute();
		}
	}
}