AlTER TABLE #__teama_news
    ADD COLUMN `creation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS modification_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS publication_date DATETIME,
    ADD COLUMN IF NOT EXISTS current_stage INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS publication_status INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_modifier INT;