<?php
namespace TheLoneBlackSheep\Component\TeamA\Site\Dispatcher;

use Joomla\CMS\Dispatcher\ComponentDispatcher;
use Joomla\CMS\Extension\Component;

\defined('_JEXEC') or die('Restricted Access');

class Dispatcher
	extends ComponentDispatcher
{
	public function dispatch() {
		parent::dispatch(); // TODO: Change the autogenerated stub
	}
}