version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo_backend
    command: mongod --auth
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Mbhj#ksf1445Mbfgqg
  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongoexpress_backend
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Mbhj#ksf1445Mbfgqg
      ME_CONFIG_MONGODB_URL: mongodb://root:Mbhj#ksf1445Mbfgqg@mongo:27017/admin

